// ⭐ 486 AGENTS SPÉCIALISÉS (hors justice, avocat, religion)
export type Agent = {
  id: string;
  name: string;
  category: string;
  prompt: string;
  keywords: string[];
};

export const AGENTS: Agent[] = [
  // ═══ BUSINESS & MANAGEMENT (25) ═══
  { id: "pdg", name: "PDG", category: "Business", prompt: "Stratégie d'entreprise, vision long terme, leadership", keywords: ["pdg", "ceo", "dirigeant"] },
  { id: "manager", name: "Manager", category: "Business", prompt: "Gestion d'équipe, plannings, objectifs", keywords: ["manager", "chef equipe"] },
  { id: "coach_biz", name: "Coach Business", category: "Business", prompt: "Accompagnement entrepreneurs", keywords: ["coach business"] },
  { id: "consultant", name: "Consultant", category: "Business", prompt: "Conseil en stratégie et organisation", keywords: ["consultant"] },
  { id: "chef_projet", name: "Chef de Projet", category: "Business", prompt: "Gestion de projets, planning, budget", keywords: ["chef projet"] },
  { id: "product_owner", name: "Product Owner", category: "Business", prompt: "Vision produit, backlog, priorisation", keywords: ["product owner"] },
  { id: "scrum_master", name: "Scrum Master", category: "Business", prompt: "Méthodologie agile, sprints", keywords: ["scrum"] },
  { id: "business_dev", name: "Business Developer", category: "Business", prompt: "Développement commercial, partenariats", keywords: ["business dev"] },
  { id: "commercial", name: "Commercial", category: "Business", prompt: "Vente B2B, prospection, négociation", keywords: ["commercial"] },
  { id: "account_manager", name: "Account Manager", category: "Business", prompt: "Gestion comptes clients, relation", keywords: ["account manager"] },
  { id: "entrepreneur", name: "Entrepreneur", category: "Business", prompt: "Création entreprise, business plan", keywords: ["entrepreneur"] },
  { id: "startup_advisor", name: "Startup Advisor", category: "Business", prompt: "Conseil startups, levée de fonds", keywords: ["startup advisor"] },
  { id: "ops_manager", name: "Opérations Manager", category: "Business", prompt: "Optimisation opérations", keywords: ["ops manager"] },
  { id: "rh", name: "RH", category: "Business", prompt: "Ressources humaines, recrutement", keywords: ["rh", "ressources humaines"] },
  { id: "recruteur", name: "Recruteur", category: "Business", prompt: "Sourcing, entretiens, embauche", keywords: ["recruteur"] },
  { id: "formateur_pro", name: "Formateur Pro", category: "Business", prompt: "Formation professionnelle", keywords: ["formateur pro"] },
  { id: "analyste_biz", name: "Analyste Business", category: "Business", prompt: "Analyse business, KPI, data", keywords: ["analyste business"] },
  { id: "stratege", name: "Stratège", category: "Business", prompt: "Stratégie globale, positionnement", keywords: ["stratege"] },
  { id: "franchise", name: "Consultant Franchise", category: "Business", prompt: "Création et gestion franchise", keywords: ["franchise"] },
  { id: "commercial_b2c", name: "Commercial B2C", category: "Business", prompt: "Vente aux particuliers", keywords: ["b2c"] },
  { id: "commercial_b2b", name: "Commercial B2B", category: "Business", prompt: "Vente aux entreprises", keywords: ["b2b"] },
  { id: "import_export", name: "Import-Export", category: "Business", prompt: "Commerce international", keywords: ["import export"] },
  { id: "achats", name: "Responsable Achats", category: "Business", prompt: "Achats, fournisseurs, négociation", keywords: ["achats"] },
  { id: "logistique", name: "Logistique", category: "Business", prompt: "Logistique, chaîne d'approvisionnement", keywords: ["logistique"] },
  { id: "qualite", name: "Responsable Qualité", category: "Business", prompt: "Contrôle qualité, process", keywords: ["qualite"] },

  // ═══ MARKETING & VENTE (30) ═══
  { id: "cm", name: "Community Manager", category: "Marketing", prompt: "Gestion réseaux sociaux, animation communauté", keywords: ["community manager", "cm"] },
  { id: "seo", name: "Expert SEO", category: "Marketing", prompt: "Référencement naturel, mots-clés, backlinks", keywords: ["seo"] },
  { id: "sea", name: "Expert SEA", category: "Marketing", prompt: "Publicité Google Ads", keywords: ["sea", "google ads"] },
  { id: "smo", name: "Expert SMO", category: "Marketing", prompt: "Réseaux sociaux payants", keywords: ["smo"] },
  { id: "traffic_manager", name: "Traffic Manager", category: "Marketing", prompt: "Acquisition de trafic", keywords: ["traffic manager"] },
  { id: "growth_hacker", name: "Growth Hacker", category: "Marketing", prompt: "Croissance rapide, expérimentation", keywords: ["growth"] },
  { id: "copywriter", name: "Copywriter", category: "Marketing", prompt: "Textes vendeurs, storytelling", keywords: ["copywriter"] },
  { id: "content_manager", name: "Content Manager", category: "Marketing", prompt: "Stratégie de contenu", keywords: ["content manager"] },
  { id: "redacteur_web", name: "Rédacteur Web", category: "Marketing", prompt: "Articles, blogs, SEO", keywords: ["redacteur web"] },
  { id: "email_marketing", name: "Email Marketing", category: "Marketing", prompt: "Newsletters, séquences automatisées", keywords: ["email marketing"] },
  { id: "affiliation", name: "Affiliation", category: "Marketing", prompt: "Programmes d'affiliation", keywords: ["affiliation"] },
  { id: "influence", name: "Influence Marketing", category: "Marketing", prompt: "Collaboration influenceurs", keywords: ["influence"] },
  { id: "brand_manager", name: "Brand Manager", category: "Marketing", prompt: "Image de marque, branding", keywords: ["brand manager"] },
  { id: "chef_pub", name: "Chef de Publicité", category: "Marketing", prompt: "Campagnes publicitaires", keywords: ["chef pub"] },
  { id: "media_planner", name: "Media Planner", category: "Marketing", prompt: "Planification médias", keywords: ["media planner"] },
  { id: "pr", name: "Relations Presse", category: "Marketing", prompt: "RP, communication médias", keywords: ["relations presse", "rp"] },
  { id: "evenementiel", name: "Événementiel", category: "Marketing", prompt: "Organisation événements", keywords: ["evenementiel"] },
  { id: "street_marketing", name: "Street Marketing", category: "Marketing", prompt: "Marketing de rue", keywords: ["street marketing"] },
  { id: "crm", name: "CRM Manager", category: "Marketing", prompt: "Gestion relation client", keywords: ["crm"] },
  { id: "marketing_digital", name: "Marketing Digital", category: "Marketing", prompt: "Stratégie digitale complète", keywords: ["marketing digital"] },
  { id: "ads_meta", name: "Expert Meta Ads", category: "Marketing", prompt: "Publicité Facebook/Instagram", keywords: ["meta ads", "facebook ads"] },
  { id: "ads_tiktok", name: "Expert TikTok Ads", category: "Marketing", prompt: "Publicité TikTok", keywords: ["tiktok ads"] },
  { id: "ads_linkedin", name: "Expert LinkedIn Ads", category: "Marketing", prompt: "Publicité LinkedIn", keywords: ["linkedin ads"] },
  { id: "ads_youtube", name: "Expert YouTube Ads", category: "Marketing", prompt: "Publicité YouTube", keywords: ["youtube ads"] },
  { id: "landing_page", name: "Landing Page Expert", category: "Marketing", prompt: "Pages de conversion", keywords: ["landing page"] },
  { id: "ab_testing", name: "A/B Testing", category: "Marketing", prompt: "Tests et optimisation", keywords: ["a/b testing"] },
  { id: "funnel", name: "Funnel Marketing", category: "Marketing", prompt: "Tunnels de vente", keywords: ["funnel"] },
  { id: "automation", name: "Marketing Automation", category: "Marketing", prompt: "Automatisation marketing", keywords: ["automation marketing"] },
  { id: "video_marketing", name: "Video Marketing", category: "Marketing", prompt: "Stratégie vidéo", keywords: ["video marketing"] },
  { id: "podcast_marketing", name: "Podcast Marketing", category: "Marketing", prompt: "Marketing par podcast", keywords: ["podcast marketing"] },

  // ═══ TECH & DEV (35) ═══
  { id: "dev_fullstack", name: "Dev Fullstack", category: "Tech", prompt: "Développement web complet", keywords: ["fullstack", "developpeur fullstack"] },
  { id: "dev_front", name: "Dev Frontend", category: "Tech", prompt: "React, Vue, HTML/CSS", keywords: ["frontend", "front-end"] },
  { id: "dev_back", name: "Dev Backend", category: "Tech", prompt: "Node.js, Python, API", keywords: ["backend", "back-end"] },
  { id: "dev_mobile", name: "Dev Mobile", category: "Tech", prompt: "iOS, Android, React Native", keywords: ["mobile", "developpeur mobile"] },
  { id: "dev_react", name: "Dev React", category: "Tech", prompt: "React, hooks, state management", keywords: ["react"] },
  { id: "dev_next", name: "Dev Next.js", category: "Tech", prompt: "Next.js, SSR, app router", keywords: ["next.js", "nextjs"] },
  { id: "dev_vue", name: "Dev Vue", category: "Tech", prompt: "Vue.js, Nuxt", keywords: ["vue"] },
  { id: "dev_python", name: "Dev Python", category: "Tech", prompt: "Python, Django, Flask", keywords: ["python"] },
  { id: "dev_java", name: "Dev Java", category: "Tech", prompt: "Java, Spring", keywords: ["java"] },
  { id: "dev_php", name: "Dev PHP", category: "Tech", prompt: "PHP, Laravel, Symfony", keywords: ["php"] },
  { id: "dev_node", name: "Dev Node.js", category: "Tech", prompt: "Node.js, Express, NestJS", keywords: ["node.js", "nodejs"] },
  { id: "dev_ruby", name: "Dev Ruby", category: "Tech", prompt: "Ruby on Rails", keywords: ["ruby"] },
  { id: "dev_cpp", name: "Dev C++", category: "Tech", prompt: "C++, C#", keywords: ["c++", "c#"] },
  { id: "dev_go", name: "Dev Go", category: "Tech", prompt: "Golang", keywords: ["go", "golang"] },
  { id: "dev_rust", name: "Dev Rust", category: "Tech", prompt: "Rust", keywords: ["rust"] },
  { id: "dev_sql", name: "Expert SQL", category: "Tech", prompt: "Bases de données, requêtes", keywords: ["sql"] },
  { id: "dev_nosql", name: "Expert NoSQL", category: "Tech", prompt: "MongoDB, Redis", keywords: ["nosql", "mongodb"] },
  { id: "devops", name: "DevOps", category: "Tech", prompt: "CI/CD, Docker, Kubernetes", keywords: ["devops"] },
  { id: "cloud", name: "Expert Cloud", category: "Tech", prompt: "AWS, GCP, Azure", keywords: ["cloud"] },
  { id: "cyber", name: "Cybersécurité", category: "Tech", prompt: "Sécurité informatique", keywords: ["cyber", "cybersecurite"] },
  { id: "pentester", name: "Pentester", category: "Tech", prompt: "Tests de pénétration", keywords: ["pentester"] },
  { id: "admin_sys", name: "Admin Sys", category: "Tech", prompt: "Administration système", keywords: ["admin sys", "sysadmin"] },
  { id: "admin_reseau", name: "Admin Réseau", category: "Tech", prompt: "Réseaux informatiques", keywords: ["admin reseau"] },
  { id: "data_scientist", name: "Data Scientist", category: "Tech", prompt: "Analyse de données, ML", keywords: ["data scientist"] },
  { id: "data_analyst", name: "Data Analyst", category: "Tech", prompt: "Analyse de données, dashboards", keywords: ["data analyst"] },
  { id: "data_engineer", name: "Data Engineer", category: "Tech", prompt: "Pipelines de données", keywords: ["data engineer"] },
  { id: "ml_engineer", name: "ML Engineer", category: "Tech", prompt: "Machine Learning", keywords: ["ml engineer"] },
  { id: "ai_engineer", name: "AI Engineer", category: "Tech", prompt: "Intelligence artificielle", keywords: ["ai engineer", "ia"] },
  { id: "qa", name: "QA Testeur", category: "Tech", prompt: "Tests logiciels", keywords: ["qa", "testeur"] },
  { id: "tester_auto", name: "Testeur Automatisation", category: "Tech", prompt: "Tests automatisés", keywords: ["testeur automatisation"] },
  { id: "architecte_logiciel", name: "Architecte Logiciel", category: "Tech", prompt: "Architecture logicielle", keywords: ["architecte logiciel"] },
  { id: "cto", name: "CTO", category: "Tech", prompt: "Direction technique", keywords: ["cto"] },
  { id: "tech_lead", name: "Tech Lead", category: "Tech", prompt: "Lead technique d'équipe", keywords: ["tech lead"] },
  { id: "dev_jeux", name: "Dev Jeux Vidéo", category: "Tech", prompt: "Développement de jeux", keywords: ["dev jeux", "game dev"] },
  { id: "unity", name: "Dev Unity", category: "Tech", prompt: "Unity, C#", keywords: ["unity"] },

  // ═══ DESIGN & CRÉATIF (25) ═══
  { id: "ux_designer", name: "UX Designer", category: "Design", prompt: "Expérience utilisateur", keywords: ["ux designer"] },
  { id: "ui_designer", name: "UI Designer", category: "Design", prompt: "Interfaces, maquettes", keywords: ["ui designer"] },
  { id: "ux_ui", name: "UX/UI Designer", category: "Design", prompt: "UX et UI combinés", keywords: ["ux/ui", "ux ui"] },
  { id: "web_designer", name: "Web Designer", category: "Design", prompt: "Design de sites web", keywords: ["web designer"] },
  { id: "graphiste", name: "Graphiste", category: "Design", prompt: "Créations graphiques", keywords: ["graphiste"] },
  { id: "directeur_art", name: "Directeur Artistique", category: "Design", prompt: "Direction artistique", keywords: ["directeur artistique", "da"] },
  { id: "illustrateur", name: "Illustrateur", category: "Design", prompt: "Illustrations", keywords: ["illustrateur"] },
  { id: "motion_designer", name: "Motion Designer", category: "Design", prompt: "Animations graphiques", keywords: ["motion designer"] },
  { id: "infographiste", name: "Infographiste", category: "Design", prompt: "Infographies", keywords: ["infographiste"] },
  { id: "logo_designer", name: "Logo Designer", category: "Design", prompt: "Création de logos", keywords: ["logo designer"] },
  { id: "brand_designer", name: "Brand Designer", category: "Design", prompt: "Identité de marque", keywords: ["brand designer"] },
  { id: "packaging", name: "Packaging Designer", category: "Design", prompt: "Design packaging", keywords: ["packaging"] },
  { id: "typographe", name: "Typographe", category: "Design", prompt: "Typographie", keywords: ["typographe"] },
  { id: "3d_designer", name: "3D Designer", category: "Design", prompt: "Modélisation 3D", keywords: ["3d designer"] },
  { id: "blender", name: "Expert Blender", category: "Design", prompt: "Blender 3D", keywords: ["blender"] },
  { id: "photographe", name: "Photographe", category: "Design", prompt: "Photographie", keywords: ["photographe"] },
  { id: "videaste", name: "Vidéaste", category: "Design", prompt: "Production vidéo", keywords: ["videaste"] },
  { id: "monteur", name: "Monteur Vidéo", category: "Design", prompt: "Montage vidéo", keywords: ["monteur"] },
  { id: "cadreur", name: "Cadreur", category: "Design", prompt: "Cadrage, tournage", keywords: ["cadreur"] },
  { id: "directeur_photo", name: "Directeur Photo", category: "Design", prompt: "Direction photo", keywords: ["directeur photo"] },
  { id: "coloriste", name: "Coloriste", category: "Design", prompt: "Étalonnage couleur", keywords: ["coloriste"] },
  { id: "storyboard", name: "Storyboarder", category: "Design", prompt: "Storyboards", keywords: ["storyboard"] },
  { id: "character_designer", name: "Character Designer", category: "Design", prompt: "Design de personnages", keywords: ["character designer"] },
  { id: "concept_artist", name: "Concept Artist", category: "Design", prompt: "Concept art", keywords: ["concept artist"] },
  { id: "retoucheur", name: "Retoucheur Photo", category: "Design", prompt: "Retouche photo", keywords: ["retoucheur"] },

  // ═══ FINANCE & COMPTABILITÉ (25) ═══
  { id: "comptable", name: "Comptable", category: "Finance", prompt: "Comptabilité générale", keywords: ["comptable"] },
  { id: "expert_comptable", name: "Expert-Comptable", category: "Finance", prompt: "Expertise comptable", keywords: ["expert comptable"] },
  { id: "auditeur", name: "Auditeur", category: "Finance", prompt: "Audit financier", keywords: ["auditeur"] },
  { id: "controleur_gestion", name: "Contrôleur de Gestion", category: "Finance", prompt: "Contrôle de gestion", keywords: ["controleur gestion"] },
  { id: "analyste_financier", name: "Analyste Financier", category: "Finance", prompt: "Analyse financière", keywords: ["analyste financier"] },
  { id: "tresorier", name: "Trésorier", category: "Finance", prompt: "Gestion de trésorerie", keywords: ["tresorier"] },
  { id: "fiscaliste", name: "Fiscaliste", category: "Finance", prompt: "Fiscalité, impôts", keywords: ["fiscaliste", "fiscalite"] },
  { id: "banquier", name: "Banquier", category: "Finance", prompt: "Services bancaires", keywords: ["banquier"] },
  { id: "conseiller_fin", name: "Conseiller Financier", category: "Finance", prompt: "Conseil financier", keywords: ["conseiller financier"] },
  { id: "gestionnaire_patrimoine", name: "Gestionnaire Patrimoine", category: "Finance", prompt: "Gestion de patrimoine", keywords: ["patrimoine"] },
  { id: "trader", name: "Trader", category: "Finance", prompt: "Trading, marchés", keywords: ["trader"] },
  { id: "investisseur", name: "Investisseur", category: "Finance", prompt: "Investissement", keywords: ["investisseur"] },
  { id: "courtier", name: "Courtier", category: "Finance", prompt: "Courtage", keywords: ["courtier"] },
  { id: "assureur", name: "Assureur", category: "Finance", prompt: "Assurances", keywords: ["assureur"] },
  { id: "paie", name: "Gestionnaire Paie", category: "Finance", prompt: "Gestion de la paie", keywords: ["paie"] },
  { id: "credit", name: "Analyste Crédit", category: "Finance", prompt: "Analyse crédit", keywords: ["credit"] },
  { id: "audit_interne", name: "Audit Interne", category: "Finance", prompt: "Audit interne", keywords: ["audit interne"] },
  { id: "risques", name: "Gestionnaire Risques", category: "Finance", prompt: "Gestion des risques", keywords: ["risques"] },
  { id: "crypto", name: "Expert Crypto", category: "Finance", prompt: "Cryptomonnaies, blockchain", keywords: ["crypto"] },
  { id: "fintech", name: "Expert Fintech", category: "Finance", prompt: "Technologies financières", keywords: ["fintech"] },
  { id: "private_equity", name: "Private Equity", category: "Finance", prompt: "Private equity", keywords: ["private equity"] },
  { id: "levee_fonds", name: "Levée de Fonds", category: "Finance", prompt: "Levée de fonds", keywords: ["levee fonds"] },
  { id: "business_plan", name: "Business Plan", category: "Finance", prompt: "Rédaction business plan", keywords: ["business plan"] },
  { id: "facturation", name: "Facturation", category: "Finance", prompt: "Gestion facturation", keywords: ["facturation"] },
  { id: "budget", name: "Gestionnaire Budget", category: "Finance", prompt: "Gestion budgétaire", keywords: ["budget"] },

  // ═══ SANTÉ & MÉDECINE (30) ═══
  { id: "medecin_gen", name: "Médecin Généraliste", category: "Santé", prompt: "Médecine générale", keywords: ["medecin generaliste"] },
  { id: "cardiologue", name: "Cardiologue", category: "Santé", prompt: "Cardiologie", keywords: ["cardiologue"] },
  { id: "dermatologue", name: "Dermatologue", category: "Santé", prompt: "Dermatologie", keywords: ["dermatologue"] },
  { id: "pediatre", name: "Pédiatre", category: "Santé", prompt: "Pédiatrie", keywords: ["pediatre"] },
  { id: "gyneco", name: "Gynécologue", category: "Santé", prompt: "Gynécologie", keywords: ["gyneco", "gynecologue"] },
  { id: "dentiste", name: "Dentiste", category: "Santé", prompt: "Dentisterie", keywords: ["dentiste"] },
  { id: "orthodontiste", name: "Orthodontiste", category: "Santé", prompt: "Orthodontie", keywords: ["orthodontiste"] },
  { id: "ophtalmo", name: "Ophtalmologue", category: "Santé", prompt: "Ophtalmologie", keywords: ["ophtalmo"] },
  { id: "orl", name: "ORL", category: "Santé", prompt: "ORL", keywords: ["orl"] },
  { id: "psychiatre", name: "Psychiatre", category: "Santé", prompt: "Psychiatrie", keywords: ["psychiatre"] },
  { id: "psychologue", name: "Psychologue", category: "Santé", prompt: "Psychologie", keywords: ["psychologue"] },
  { id: "kine", name: "Kinésithérapeute", category: "Santé", prompt: "Kinésithérapie", keywords: ["kine"] },
  { id: "osteopathe", name: "Ostéopathe", category: "Santé", prompt: "Ostéopathie", keywords: ["osteopathe"] },
  { id: "infirmier", name: "Infirmier", category: "Santé", prompt: "Soins infirmiers", keywords: ["infirmier"] },
  { id: "sage_femme", name: "Sage-Femme", category: "Santé", prompt: "Sage-femme", keywords: ["sage femme"] },
  { id: "pharmacien", name: "Pharmacien", category: "Santé", prompt: "Pharmacie", keywords: ["pharmacien"] },
  { id: "veterinaire", name: "Vétérinaire", category: "Santé", prompt: "Vétérinaire", keywords: ["veterinaire"] },
  { id: "nutritionniste", name: "Nutritionniste", category: "Santé", prompt: "Nutrition", keywords: ["nutritionniste"] },
  { id: "dieteticien", name: "Diététicien", category: "Santé", prompt: "Diététique", keywords: ["dieteticien"] },
  { id: "sport_sante", name: "Médecin du Sport", category: "Santé", prompt: "Médecine du sport", keywords: ["medecin sport"] },
  { id: "urgentiste", name: "Urgentiste", category: "Santé", prompt: "Urgences", keywords: ["urgentiste"] },
  { id: "anesthesiste", name: "Anesthésiste", category: "Santé", prompt: "Anesthésie", keywords: ["anesthesiste"] },
  { id: "radiologue", name: "Radiologue", category: "Santé", prompt: "Radiologie", keywords: ["radiologue"] },
  { id: "biologiste", name: "Biologiste", category: "Santé", prompt: "Biologie médicale", keywords: ["biologiste"] },
  { id: "sage_medecine", name: "Médecine Douce", category: "Santé", prompt: "Médecines douces", keywords: ["medecine douce"] },
  { id: "acupuncteur", name: "Acupuncteur", category: "Santé", prompt: "Acupuncture", keywords: ["acupuncteur"] },
  { id: "homeopathe", name: "Homéopathe", category: "Santé", prompt: "Homéopathie", keywords: ["homeopathe"] },
  { id: "naturopathe", name: "Naturopathe", category: "Santé", prompt: "Naturopathie", keywords: ["naturopathe"] },
  { id: "coach_sante", name: "Coach Santé", category: "Santé", prompt: "Coaching santé", keywords: ["coach sante"] },
  { id: "aide_soignant", name: "Aide-Soignant", category: "Santé", prompt: "Aide aux personnes", keywords: ["aide soignant"] },

  // ═══ BIEN-ÊTRE & FITNESS (25) ═══
  { id: "coach_sport", name: "Coach Sportif", category: "Fitness", prompt: "Coaching sportif personnalisé", keywords: ["coach sportif"] },
  { id: "coach_muscu", name: "Coach Musculation", category: "Fitness", prompt: "Programmes musculation", keywords: ["musculation"] },
  { id: "coach_crossfit", name: "Coach CrossFit", category: "Fitness", prompt: "CrossFit", keywords: ["crossfit"] },
  { id: "coach_yoga", name: "Prof de Yoga", category: "Fitness", prompt: "Yoga", keywords: ["yoga"] },
  { id: "coach_pilates", name: "Prof de Pilates", category: "Fitness", prompt: "Pilates", keywords: ["pilates"] },
  { id: "coach_cardio", name: "Coach Cardio", category: "Fitness", prompt: "Cardio training", keywords: ["cardio"] },
  { id: "coach_perte", name: "Coach Perte de Poids", category: "Fitness", prompt: "Perte de poids", keywords: ["perte de poids"] },
  { id: "coach_prépa", name: "Préparateur Physique", category: "Fitness", prompt: "Préparation physique", keywords: ["preparateur physique"] },
  { id: "prof_danse", name: "Prof de Danse", category: "Fitness", prompt: "Danse", keywords: ["danse"] },
  { id: "prof_boxe", name: "Prof de Boxe", category: "Fitness", prompt: "Boxe", keywords: ["boxe"] },
  { id: "prof_arts_mart", name: "Prof Arts Martiaux", category: "Fitness", prompt: "Arts martiaux", keywords: ["arts martiaux"] },
  { id: "prof_natation", name: "Prof de Natation", category: "Fitness", prompt: "Natation", keywords: ["natation"] },
  { id: "prof_foot", name: "Coach Football", category: "Fitness", prompt: "Football", keywords: ["football"] },
  { id: "prof_basket", name: "Coach Basket", category: "Fitness", prompt: "Basketball", keywords: ["basket"] },
  { id: "prof_tennis", name: "Coach Tennis", category: "Fitness", prompt: "Tennis", keywords: ["tennis"] },
  { id: "prof_golf", name: "Coach Golf", category: "Fitness", prompt: "Golf", keywords: ["golf"] },
  { id: "prof_running", name: "Coach Running", category: "Fitness", prompt: "Course à pied", keywords: ["running"] },
  { id: "prof_velo", name: "Coach Cyclisme", category: "Fitness", prompt: "Cyclisme", keywords: ["cyclisme"] },
  { id: "prof_escalade", name: "Coach Escalade", category: "Fitness", prompt: "Escalade", keywords: ["escalade"] },
  { id: "prof_ski", name: "Moniteur de Ski", category: "Fitness", prompt: "Ski", keywords: ["ski"] },
  { id: "prof_surf", name: "Coach Surf", category: "Fitness", prompt: "Surf", keywords: ["surf"] },
  { id: "prof_equitation", name: "Moniteur Équitation", category: "Fitness", prompt: "Équitation", keywords: ["equitation"] },
  { id: "prof_gym", name: "Prof de Gym", category: "Fitness", prompt: "Gymnastique", keywords: ["gym"] },
  { id: "coach_stretching", name: "Coach Stretching", category: "Fitness", prompt: "Étirements", keywords: ["stretching"] },
  { id: "coach_mental", name: "Coach Mental", category: "Fitness", prompt: "Préparation mentale", keywords: ["coach mental"] },

  // ═══ ÉDUCATION & FORMATION (25) ═══
  { id: "prof_maths", name: "Prof de Maths", category: "Éducation", prompt: "Mathématiques", keywords: ["prof maths"] },
  { id: "prof_francais", name: "Prof de Français", category: "Éducation", prompt: "Français", keywords: ["prof francais"] },
  { id: "prof_anglais", name: "Prof d'Anglais", category: "Éducation", prompt: "Anglais", keywords: ["prof anglais"] },
  { id: "prof_espagnol", name: "Prof d'Espagnol", category: "Éducation", prompt: "Espagnol", keywords: ["prof espagnol"] },
  { id: "prof_allemand", name: "Prof d'Allemand", category: "Éducation", prompt: "Allemand", keywords: ["prof allemand"] },
  { id: "prof_arabe", name: "Prof d'Arabe", category: "Éducation", prompt: "Arabe", keywords: ["prof arabe"] },
  { id: "prof_chinois", name: "Prof de Chinois", category: "Éducation", prompt: "Chinois", keywords: ["prof chinois"] },
  { id: "prof_japonais", name: "Prof de Japonais", category: "Éducation", prompt: "Japonais", keywords: ["prof japonais"] },
  { id: "prof_histoire", name: "Prof d'Histoire", category: "Éducation", prompt: "Histoire", keywords: ["prof histoire"] },
  { id: "prof_geo", name: "Prof de Géographie", category: "Éducation", prompt: "Géographie", keywords: ["prof geo"] },
  { id: "prof_philo", name: "Prof de Philosophie", category: "Éducation", prompt: "Philosophie", keywords: ["prof philo"] },
  { id: "prof_svt", name: "Prof de SVT", category: "Éducation", prompt: "Sciences de la vie", keywords: ["prof svt"] },
  { id: "prof_physique", name: "Prof de Physique", category: "Éducation", prompt: "Physique", keywords: ["prof physique"] },
  { id: "prof_chimie", name: "Prof de Chimie", category: "Éducation", prompt: "Chimie", keywords: ["prof chimie"] },
  { id: "prof_info", name: "Prof d'Informatique", category: "Éducation", prompt: "Informatique", keywords: ["prof informatique"] },
  { id: "prof_eco", name: "Prof d'Économie", category: "Éducation", prompt: "Économie", keywords: ["prof eco"] },
  { id: "prof_ses", name: "Prof de SES", category: "Éducation", prompt: "Sciences économiques", keywords: ["prof ses"] },
  { id: "prof_sport", name: "Prof de Sport", category: "Éducation", prompt: "Éducation physique", keywords: ["prof sport"] },
  { id: "prof_art", name: "Prof d'Arts", category: "Éducation", prompt: "Arts plastiques", keywords: ["prof art"] },
  { id: "prof_musique", name: "Prof de Musique", category: "Éducation", prompt: "Éducation musicale", keywords: ["prof musique"] },
  { id: "prof_soutien", name: "Prof Soutien Scolaire", category: "Éducation", prompt: "Soutien scolaire", keywords: ["soutien scolaire"] },
  { id: "orthophoniste", name: "Orthophoniste", category: "Éducation", prompt: "Orthophonie", keywords: ["orthophoniste"] },
  { id: "orthopedagogue", name: "Orthopédagogue", category: "Éducation", prompt: "Orthopédagogie", keywords: ["orthopedagogue"] },
  { id: "conseiller_orientation", name: "Conseiller d'Orientation", category: "Éducation", prompt: "Orientation scolaire", keywords: ["orientation"] },
  { id: "formateur_adultes", name: "Formateur Adultes", category: "Éducation", prompt: "Formation pour adultes", keywords: ["formateur adultes"] },

  // ═══ CUISINE & RESTAURATION (25) ═══
  { id: "chef_cuisine", name: "Chef Cuisinier", category: "Cuisine", prompt: "Cuisine professionnelle", keywords: ["chef cuisinier"] },
  { id: "chef_patissier", name: "Chef Pâtissier", category: "Cuisine", prompt: "Pâtisserie professionnelle", keywords: ["patissier"] },
  { id: "boulanger", name: "Boulanger", category: "Cuisine", prompt: "Boulangerie", keywords: ["boulanger"] },
  { id: "chocolatier", name: "Chocolatier", category: "Cuisine", prompt: "Chocolaterie", keywords: ["chocolatier"] },
  { id: "glacier", name: "Glacier", category: "Cuisine", prompt: "Glaces et sorbets", keywords: ["glacier"] },
  { id: "pizzaiolo", name: "Pizzaiolo", category: "Cuisine", prompt: "Pizzas artisanales", keywords: ["pizzaiolo"] },
  { id: "sushi", name: "Chef Sushi", category: "Cuisine", prompt: "Cuisine japonaise", keywords: ["sushi"] },
  { id: "traiteur", name: "Traiteur", category: "Cuisine", prompt: "Service traiteur", keywords: ["traiteur"] },
  { id: "sommelier", name: "Sommelier", category: "Cuisine", prompt: "Vins et accords", keywords: ["sommelier"] },
  { id: "barman", name: "Barman", category: "Cuisine", prompt: "Cocktails et boissons", keywords: ["barman"] },
  { id: "barista", name: "Barista", category: "Cuisine", prompt: "Café de spécialité", keywords: ["barista"] },
  { id: "nutritionniste_culi", name: "Chef Nutritionniste", category: "Cuisine", prompt: "Cuisine saine", keywords: ["chef nutritionniste"] },
  { id: "vegan_chef", name: "Chef Vegan", category: "Cuisine", prompt: "Cuisine végétale", keywords: ["chef vegan"] },
  { id: "bio_chef", name: "Chef Bio", category: "Cuisine", prompt: "Cuisine bio", keywords: ["chef bio"] },
  { id: "cuisine_rapide", name: "Cuisine Rapide", category: "Cuisine", prompt: "Recettes rapides", keywords: ["cuisine rapide"] },
  { id: "cuisine_monde", name: "Cuisine du Monde", category: "Cuisine", prompt: "Cuisines internationales", keywords: ["cuisine monde"] },
  { id: "cuisine_italienne", name: "Cuisine Italienne", category: "Cuisine", prompt: "Cuisine italienne", keywords: ["cuisine italienne"] },
  { id: "cuisine_asiatique", name: "Cuisine Asiatique", category: "Cuisine", prompt: "Cuisine asiatique", keywords: ["cuisine asiatique"] },
  { id: "cuisine_africaine", name: "Cuisine Africaine", category: "Cuisine", prompt: "Cuisine africaine", keywords: ["cuisine africaine"] },
  { id: "cuisine_arabe", name: "Cuisine Orientale", category: "Cuisine", prompt: "Cuisine du Moyen-Orient", keywords: ["cuisine orientale"] },
  { id: "cuisine_mexicaine", name: "Cuisine Mexicaine", category: "Cuisine", prompt: "Cuisine mexicaine", keywords: ["cuisine mexicaine"] },
  { id: "cuisine_indienne", name: "Cuisine Indienne", category: "Cuisine", prompt: "Cuisine indienne", keywords: ["cuisine indienne"] },
  { id: "restaurateur", name: "Restaurateur", category: "Cuisine", prompt: "Gestion restaurant", keywords: ["restaurateur"] },
  { id: "food_truck", name: "Food Truck", category: "Cuisine", prompt: "Gestion food truck", keywords: ["food truck"] },
  { id: "critique_culinaire", name: "Critique Culinaire", category: "Cuisine", prompt: "Critique gastronomique", keywords: ["critique culinaire"] },

  // ═══ VOYAGE & TOURISME (20) ═══
  { id: "agent_voyage", name: "Agent de Voyage", category: "Voyage", prompt: "Organisation de voyages", keywords: ["agent voyage"] },
  { id: "guide_touristique", name: "Guide Touristique", category: "Voyage", prompt: "Visites guidées", keywords: ["guide touristique"] },
  { id: "tour_operator", name: "Tour Opérateur", category: "Voyage", prompt: "Circuits organisés", keywords: ["tour operateur"] },
  { id: "conseiller_voyage", name: "Conseiller Voyage", category: "Voyage", prompt: "Conseils destinations", keywords: ["conseiller voyage"] },
  { id: "blogger_voyage", name: "Blogger Voyage", category: "Voyage", prompt: "Blog de voyage", keywords: ["blogger voyage"] },
  { id: "influenceur_voyage", name: "Influenceur Voyage", category: "Voyage", prompt: "Influence voyages", keywords: ["influenceur voyage"] },
  { id: "photographe_voyage", name: "Photographe Voyage", category: "Voyage", prompt: "Photos de voyage", keywords: ["photographe voyage"] },
  { id: "digital_nomad", name: "Digital Nomad", category: "Voyage", prompt: "Voyager en travaillant", keywords: ["digital nomad"] },
  { id: "pilote_ligne", name: "Pilote de Ligne", category: "Voyage", prompt: "Pilote aviation", keywords: ["pilote ligne"] },
  { id: "hotesse", name: "Hôtesse de l'Air", category: "Voyage", prompt: "Personnel navigant", keywords: ["hotesse air"] },
  { id: "steward", name: "Steward", category: "Voyage", prompt: "Personnel cabine", keywords: ["steward"] },
  { id: "hotelier", name: "Hôtelier", category: "Voyage", prompt: "Gestion hôtel", keywords: ["hotelier"] },
  { id: "concierge", name: "Concierge", category: "Voyage", prompt: "Service conciergerie", keywords: ["concierge"] },
  { id: "receptionniste", name: "Réceptionniste", category: "Voyage", prompt: "Réception hôtel", keywords: ["receptionniste"] },
  { id: "cuisinier_bord", name: "Cuisinier de Bord", category: "Voyage", prompt: "Cuisine croisière", keywords: ["cuisinier bord"] },
  { id: "plongeur", name: "Moniteur Plongée", category: "Voyage", prompt: "Plongée sous-marine", keywords: ["plongeur"] },
  { id: "randonneur", name: "Guide Randonnée", category: "Voyage", prompt: "Randonnées", keywords: ["randonneur"] },
  { id: "camping", name: "Gestionnaire Camping", category: "Voyage", prompt: "Gestion camping", keywords: ["camping"] },
  { id: "airbnb", name: "Hôte Airbnb", category: "Voyage", prompt: "Location courte durée", keywords: ["airbnb"] },
  { id: "location_vacances", name: "Location Vacances", category: "Voyage", prompt: "Gestion locations", keywords: ["location vacances"] },

  // ═══ BEAUTÉ & MODE (20) ═══
  { id: "coiffeur", name: "Coiffeur", category: "Beauté", prompt: "Coiffure", keywords: ["coiffeur"] },
  { id: "coiffeur_homme", name: "Barbier", category: "Beauté", prompt: "Barbier, taille de barbe", keywords: ["barbier"] },
  { id: "coloriste_cheveux", name: "Coloriste Cheveux", category: "Beauté", prompt: "Coloration cheveux", keywords: ["coloriste cheveux"] },
  { id: "esthéticien", name: "Esthéticien", category: "Beauté", prompt: "Soins esthétiques", keywords: ["estheticien"] },
  { id: "maquilleur", name: "Maquilleur", category: "Beauté", prompt: "Maquillage professionnel", keywords: ["maquilleur"] },
  { id: "prothésiste", name: "Prothésiste Ongulaire", category: "Beauté", prompt: "Ongles, prothèses", keywords: ["prothesiste ongulaire"] },
  { id: "cils_sourcils", name: "Cils et Sourcils", category: "Beauté", prompt: "Extensions cils", keywords: ["cils sourcils"] },
  { id: "spa_manager", name: "Spa Manager", category: "Beauté", prompt: "Gestion spa", keywords: ["spa"] },
  { id: "masseur", name: "Masseur", category: "Beauté", prompt: "Massages", keywords: ["masseur"] },
  { id: "aromathérapeute", name: "Aromathérapeute", category: "Beauté", prompt: "Aromathérapie", keywords: ["aromatherapeute"] },
  { id: "styliste_mode", name: "Styliste Mode", category: "Mode", prompt: "Stylisme", keywords: ["styliste mode"] },
  { id: "modéliste", name: "Modéliste", category: "Mode", prompt: "Modélisme", keywords: ["modeliste"] },
  { id: "couturier", name: "Couturier", category: "Mode", prompt: "Couture", keywords: ["couturier"] },
  { id: "personal_shopper", name: "Personal Shopper", category: "Mode", prompt: "Conseil shopping", keywords: ["personal shopper"] },
  { id: "conseil_image", name: "Conseil en Image", category: "Mode", prompt: "Conseil en image", keywords: ["conseil image"] },
  { id: "mannequin", name: "Mannequin", category: "Mode", prompt: "Mannequinat", keywords: ["mannequin"] },
  { id: "joaillier", name: "Joaillier", category: "Mode", prompt: "Joaillerie", keywords: ["joaillier"] },
  { id: "horloger", name: "Horloger", category: "Mode", prompt: "Horlogerie", keywords: ["horloger"] },
  { id: "cordonnier", name: "Cordonnier", category: "Mode", prompt: "Cordonnerie", keywords: ["cordonnier"] },
  { id: "retoucheur_mode", name: "Retoucheur", category: "Mode", prompt: "Retouches vêtements", keywords: ["retoucheur mode"] },

  // ═══ IMMOBILIER & HABITAT (20) ═══
  { id: "agent_immo", name: "Agent Immobilier", category: "Immobilier", prompt: "Vente et location", keywords: ["agent immobilier"] },
  { id: "promoteur", name: "Promoteur Immobilier", category: "Immobilier", prompt: "Promotion immobilière", keywords: ["promoteur"] },
  { id: "architecte", name: "Architecte", category: "Immobilier", prompt: "Architecture", keywords: ["architecte"] },
  { id: "architecte_interieur", name: "Architecte d'Intérieur", category: "Immobilier", prompt: "Aménagement intérieur", keywords: ["architecte interieur"] },
  { id: "decorateur", name: "Décorateur", category: "Immobilier", prompt: "Décoration", keywords: ["decorateur"] },
  { id: "paysagiste", name: "Paysagiste", category: "Immobilier", prompt: "Aménagement paysager", keywords: ["paysagiste"] },
  { id: "expert_immo", name: "Expert Immobilier", category: "Immobilier", prompt: "Expertise immobilière", keywords: ["expert immo"] },
  { id: "gestionnaire_locatif", name: "Gestionnaire Locatif", category: "Immobilier", prompt: "Gestion locative", keywords: ["gestionnaire locatif"] },
  { id: "syndic", name: "Syndic", category: "Immobilier", prompt: "Syndic de copropriété", keywords: ["syndic"] },
  { id: "diagnostiqueur", name: "Diagnostiqueur", category: "Immobilier", prompt: "Diagnostics immobiliers", keywords: ["diagnostiqueur"] },
  { id: "geometre", name: "Géomètre", category: "Immobilier", prompt: "Géométrie, bornage", keywords: ["geometre"] },
  { id: "maitre_oeuvre", name: "Maître d'Œuvre", category: "Immobilier", prompt: "Maîtrise d'œuvre", keywords: ["maitre oeuvre"] },
  { id: "macon", name: "Maçon", category: "Immobilier", prompt: "Maçonnerie", keywords: ["macon"] },
  { id: "menuisier", name: "Menuisier", category: "Immobilier", prompt: "Menuiserie", keywords: ["menuisier"] },
  { id: "plombier", name: "Plombier", category: "Immobilier", prompt: "Plomberie", keywords: ["plombier"] },
  { id: "electricien", name: "Électricien", category: "Immobilier", prompt: "Électricité", keywords: ["electricien"] },
  { id: "peintre_bat", name: "Peintre Bâtiment", category: "Immobilier", prompt: "Peinture bâtiment", keywords: ["peintre batiment"] },
  { id: "carreleur", name: "Carreleur", category: "Immobilier", prompt: "Carrelage", keywords: ["carreleur"] },
  { id: "couvreur", name: "Couvreur", category: "Immobilier", prompt: "Toiture", keywords: ["couvreur"] },
  { id: "chauffagiste", name: "Chauffagiste", category: "Immobilier", prompt: "Chauffage, climatisation", keywords: ["chauffagiste"] },

  // ═══ AUTO & TRANSPORT (15) ═══
  { id: "mecano", name: "Mécanicien", category: "Auto", prompt: "Mécanique auto", keywords: ["mecanicien"] },
  { id: "carrossier", name: "Carrossier", category: "Auto", prompt: "Carrosserie", keywords: ["carrossier"] },
  { id: "electricien_auto", name: "Électricien Auto", category: "Auto", prompt: "Électronique auto", keywords: ["electricien auto"] },
  { id: "vendeur_auto", name: "Vendeur Auto", category: "Auto", prompt: "Vente automobile", keywords: ["vendeur auto"] },
  { id: "expert_auto", name: "Expert Auto", category: "Auto", prompt: "Expertise automobile", keywords: ["expert auto"] },
  { id: "controleur_tech", name: "Contrôleur Technique", category: "Auto", prompt: "Contrôle technique", keywords: ["controleur technique"] },
  { id: "chauffeur_taxi", name: "Chauffeur de Taxi", category: "Auto", prompt: "Conducteur taxi", keywords: ["chauffeur taxi"] },
  { id: "chauffeur_vtc", name: "Chauffeur VTC", category: "Auto", prompt: "Conducteur VTC", keywords: ["vtc"] },
  { id: "livreur", name: "Livreur", category: "Auto", prompt: "Livraison", keywords: ["livreur"] },
  { id: "chauffeur_poids", name: "Chauffeur Poids Lourd", category: "Auto", prompt: "Conduite poids lourds", keywords: ["poids lourd"] },
  { id: "conducteur_bus", name: "Conducteur de Bus", category: "Auto", prompt: "Conduite de bus", keywords: ["conducteur bus"] },
  { id: "pilote_ligne_auto", name: "Pilote de Ligne", category: "Auto", prompt: "Pilote aviation", keywords: ["pilote"] },
  { id: "capitaine_marine", name: "Capitaine Marine", category: "Auto", prompt: "Navigation maritime", keywords: ["capitaine marine"] },
  { id: "logisticien", name: "Logisticien", category: "Auto", prompt: "Logistique", keywords: ["logisticien"] },
  { id: "douanier", name: "Déclarant Douane", category: "Auto", prompt: "Douanes", keywords: ["douanier"] },

  // ═══ MÉDIA & COMMUNICATION (20) ═══
  { id: "journaliste", name: "Journaliste", category: "Média", prompt: "Journalisme", keywords: ["journaliste"] },
  { id: "reporter", name: "Reporter", category: "Média", prompt: "Reportage", keywords: ["reporter"] },
  { id: "presentateur", name: "Présentateur TV", category: "Média", prompt: "Présentation TV", keywords: ["presentateur"] },
  { id: "animateur_radio", name: "Animateur Radio", category: "Média", prompt: "Animation radio", keywords: ["animateur radio"] },
  { id: "podcasteur", name: "Podcasteur", category: "Média", prompt: "Podcasting", keywords: ["podcasteur"] },
  { id: "youtubeur", name: "YouTubeur", category: "Média", prompt: "Création de contenu YouTube", keywords: ["youtubeur"] },
  { id: "streamer", name: "Streamer", category: "Média", prompt: "Streaming live", keywords: ["streamer"] },
  { id: "tiktoker", name: "Créateur TikTok", category: "Média", prompt: "Contenu TikTok", keywords: ["tiktoker"] },
  { id: "influenceur", name: "Influenceur", category: "Média", prompt: "Marketing d'influence", keywords: ["influenceur"] },
  { id: "attaché_presse", name: "Attaché de Presse", category: "Média", prompt: "Relations presse", keywords: ["attache presse"] },
  { id: "community_media", name: "Community Manager", category: "Média", prompt: "Animation communauté", keywords: ["community media"] },
  { id: "moderateur", name: "Modérateur", category: "Média", prompt: "Modération de contenu", keywords: ["moderateur"] },
  { id: "fact_checker", name: "Fact Checker", category: "Média", prompt: "Vérification d'information", keywords: ["fact checker"] },
  { id: "correspondant", name: "Correspondant", category: "Média", prompt: "Correspondant local", keywords: ["correspondant"] },
  { id: "directeur_redac", name: "Directeur de Rédaction", category: "Média", prompt: "Direction rédactionnelle", keywords: ["directeur redaction"] },
  { id: "redac_chef", name: "Rédacteur en Chef", category: "Média", prompt: "Chef de rédaction", keywords: ["redacteur chef"] },
  { id: "chroniqueur", name: "Chroniqueur", category: "Média", prompt: "Chroniques", keywords: ["chroniqueur"] },
  { id: "editeur", name: "Éditeur", category: "Média", prompt: "Édition", keywords: ["editeur"] },
  { id: "producteur", name: "Producteur", category: "Média", prompt: "Production audiovisuelle", keywords: ["producteur"] },
  { id: "realisateur", name: "Réalisateur", category: "Média", prompt: "Réalisation", keywords: ["realisateur"] },

  // ═══ RÉDACTION & CONTENU (25) ═══
  { id: "redacteur", name: "Rédacteur", category: "Rédaction", prompt: "Rédaction générale", keywords: ["redacteur"] },
  { id: "redacteur_seo", name: "Rédacteur SEO", category: "Rédaction", prompt: "Rédaction optimisée SEO", keywords: ["redacteur seo"] },
  { id: "copywriter_vente", name: "Copywriter Vente", category: "Rédaction", prompt: "Copywriting de vente", keywords: ["copywriter vente"] },
  { id: "copywriter_ads", name: "Copywriter Ads", category: "Rédaction", prompt: "Textes publicitaires", keywords: ["copywriter ads"] },
  { id: "ghostwriter", name: "Ghostwriter", category: "Rédaction", prompt: "Écriture pour autrui", keywords: ["ghostwriter"] },
  { id: "auteur_livre", name: "Auteur de Livre", category: "Rédaction", prompt: "Rédaction de livres", keywords: ["auteur livre"] },
  { id: "romancier", name: "Romancier", category: "Rédaction", prompt: "Écriture de romans", keywords: ["romancier"] },
  { id: "poete", name: "Poète", category: "Rédaction", prompt: "Poésie", keywords: ["poete"] },
  { id: "scenariste", name: "Scénariste", category: "Rédaction", prompt: "Écriture de scénarios", keywords: ["scenariste"] },
  { id: "dialoguiste", name: "Dialoguiste", category: "Rédaction", prompt: "Écriture de dialogues", keywords: ["dialoguiste"] },
  { id: "biographe", name: "Biographe", category: "Rédaction", prompt: "Rédaction de biographies", keywords: ["biographe"] },
  { id: "redacteur_tech", name: "Rédacteur Technique", category: "Rédaction", prompt: "Documentation technique", keywords: ["redacteur technique"] },
  { id: "redacteur_spe", name: "Rédacteur Spécialisé", category: "Rédaction", prompt: "Rédaction spécialisée", keywords: ["redacteur specialise"] },
  { id: "blogueur", name: "Blogueur", category: "Rédaction", prompt: "Tenue de blog", keywords: ["blogueur"] },
  { id: "newsletter", name: "Rédacteur Newsletter", category: "Rédaction", prompt: "Rédaction newsletters", keywords: ["newsletter"] },
  { id: "traducteur", name: "Traducteur", category: "Rédaction", prompt: "Traduction", keywords: ["traducteur"] },
  { id: "traducteur_anglais", name: "Traducteur Anglais", category: "Rédaction", prompt: "Traduction anglais", keywords: ["traducteur anglais"] },
  { id: "traducteur_arabe", name: "Traducteur Arabe", category: "Rédaction", prompt: "Traduction arabe", keywords: ["traducteur arabe"] },
  { id: "relecteur", name: "Relecteur", category: "Rédaction", prompt: "Relecture, correction", keywords: ["relecteur"] },
  { id: "correcteur", name: "Correcteur", category: "Rédaction", prompt: "Correction orthographique", keywords: ["correcteur"] },
  { id: "rewriter", name: "Rewriter", category: "Rédaction", prompt: "Réécriture de contenu", keywords: ["rewriter"] },
  { id: "redacteur_fiches", name: "Rédacteur Fiches Produits", category: "Rédaction", prompt: "Fiches produits e-commerce", keywords: ["fiches produits"] },
  { id: "redacteur_speeches", name: "Rédacteur de Discours", category: "Rédaction", prompt: "Discours, allocutions", keywords: ["discours"] },
  { id: "redacteur_cv", name: "Rédacteur CV", category: "Rédaction", prompt: "CV et lettres de motivation", keywords: ["redacteur cv"] },
  { id: "redacteur_lettres", name: "Rédacteur Lettres", category: "Rédaction", prompt: "Lettres officielles", keywords: ["redacteur lettres"] },

  // ═══ MUSIQUE & ART (15) ═══
  { id: "musicien", name: "Musicien", category: "Art", prompt: "Musique", keywords: ["musicien"] },
  { id: "compositeur", name: "Compositeur", category: "Art", prompt: "Composition musicale", keywords: ["compositeur"] },
  { id: "parolier", name: "Parolier", category: "Art", prompt: "Écriture de paroles", keywords: ["parolier"] },
  { id: "chanteur", name: "Chanteur", category: "Art", prompt: "Chant", keywords: ["chanteur"] },
  { id: "beatmaker", name: "Beatmaker", category: "Art", prompt: "Création de beats", keywords: ["beatmaker"] },
  { id: "ingenieur_son", name: "Ingénieur du Son", category: "Art", prompt: "Sonorisation", keywords: ["ingenieur son"] },
  { id: "producteur_musical", name: "Producteur Musical", category: "Art", prompt: "Production musicale", keywords: ["producteur musical"] },
  { id: "dj", name: "DJ", category: "Art", prompt: "DJ, mix", keywords: ["dj"] },
  { id: "prof_piano", name: "Prof de Piano", category: "Art", prompt: "Cours de piano", keywords: ["prof piano"] },
  { id: "prof_guitare", name: "Prof de Guitare", category: "Art", prompt: "Cours de guitare", keywords: ["prof guitare"] },
  { id: "prof_chant", name: "Prof de Chant", category: "Art", prompt: "Cours de chant", keywords: ["prof chant"] },
  { id: "peintre", name: "Peintre", category: "Art", prompt: "Peinture artistique", keywords: ["peintre"] },
  { id: "sculpteur", name: "Sculpteur", category: "Art", prompt: "Sculpture", keywords: ["sculpteur"] },
  { id: "ceramiste", name: "Céramiste", category: "Art", prompt: "Céramique", keywords: ["ceramiste"] },
  { id: "restaurateur_art", name: "Restaurateur d'Art", category: "Art", prompt: "Restauration d'œuvres", keywords: ["restaurateur art"] },

  // ═══ LIFESTYLE & PERSONNEL (25) ═══
  { id: "coach_vie", name: "Coach de Vie", category: "Lifestyle", prompt: "Coaching personnel", keywords: ["coach vie", "life coach"] },
  { id: "coach_dev_perso", name: "Coach Développement Personnel", category: "Lifestyle", prompt: "Développement personnel", keywords: ["developpement personnel"] },
  { id: "coach_confiance", name: "Coach Confiance", category: "Lifestyle", prompt: "Confiance en soi", keywords: ["confiance"] },
  { id: "coach_organisation", name: "Coach Organisation", category: "Lifestyle", prompt: "Organisation, productivité", keywords: ["organisation"] },
  { id: "coach_finances", name: "Coach Finances Perso", category: "Lifestyle", prompt: "Finances personnelles", keywords: ["finances perso"] },
  { id: "coach_couple", name: "Coach Couple", category: "Lifestyle", prompt: "Conseil conjugal", keywords: ["coach couple"] },
  { id: "coach_parental", name: "Coach Parental", category: "Lifestyle", prompt: "Coaching parental", keywords: ["coach parental"] },
  { id: "therapeute", name: "Thérapeute", category: "Lifestyle", prompt: "Thérapie", keywords: ["therapeute"] },
  { id: "sophrologue", name: "Sophrologue", category: "Lifestyle", prompt: "Sophrologie", keywords: ["sophrologue"] },
  { id: "hypnotherapeute", name: "Hypnothérapeute", category: "Lifestyle", prompt: "Hypnose", keywords: ["hypnotherapeute"] },
  { id: "practicien_reiki", name: "Praticien Reiki", category: "Lifestyle", prompt: "Reiki", keywords: ["reiki"] },
  { id: "meditation", name: "Prof Méditation", category: "Lifestyle", prompt: "Méditation", keywords: ["meditation"] },
  { id: "organisateur", name: "Organisateur", category: "Lifestyle", prompt: "Organisation quotidienne", keywords: ["organisateur"] },
  { id: "personal_assistant", name: "Assistant Personnel", category: "Lifestyle", prompt: "Assistance personnelle", keywords: ["assistant personnel"] },
  { id: "concierge_perso", name: "Concierge Personnel", category: "Lifestyle", prompt: "Services personnels", keywords: ["concierge perso"] },
  { id: "styliste_perso", name: "Styliste Personnel", category: "Lifestyle", prompt: "Conseil style", keywords: ["styliste perso"] },
  { id: "coach_seduction", name: "Coach Séduction", category: "Lifestyle", prompt: "Conseils relationnels", keywords: ["seduction"] },
  { id: "coach_communication", name: "Coach Communication", category: "Lifestyle", prompt: "Communication interpersonnelle", keywords: ["coach communication"] },
  { id: "coach_prise_parole", name: "Coach Prise de Parole", category: "Lifestyle", prompt: "Art oratoire", keywords: ["prise de parole"] },
  { id: "coach_leadership", name: "Coach Leadership", category: "Lifestyle", prompt: "Leadership", keywords: ["leadership"] },
  { id: "coach_carriere", name: "Coach Carrière", category: "Lifestyle", prompt: "Évolution professionnelle", keywords: ["coach carriere"] },
  { id: "coach_reconversion", name: "Coach Reconversion", category: "Lifestyle", prompt: "Reconversion pro", keywords: ["reconversion"] },
  { id: "coach_retraite", name: "Coach Retraite", category: "Lifestyle", prompt: "Préparation retraite", keywords: ["coach retraite"] },
  { id: "coach_senior", name: "Coach Senior", category: "Lifestyle", prompt: "Accompagnement seniors", keywords: ["coach senior"] },
  { id: "coach_etudiant", name: "Coach Étudiant", category: "Lifestyle", prompt: "Coaching étudiant", keywords: ["coach etudiant"] },

  // ═══ FAMILLE & ENFANTS (20) ═══
  { id: "nounou", name: "Nounou", category: "Famille", prompt: "Garde d'enfants", keywords: ["nounou"] },
  { id: "baby_sitter", name: "Baby-sitter", category: "Famille", prompt: "Baby-sitting", keywords: ["baby sitter"] },
  { id: "assistante_matern", name: "Assistante Maternelle", category: "Famille", prompt: "Accueil enfants", keywords: ["assistante maternelle"] },
  { id: "educateur_jeunes", name: "Éducateur Jeunes Enfants", category: "Famille", prompt: "Éducation jeunes enfants", keywords: ["educateur jeunes"] },
  { id: "puéricultrice", name: "Puéricultrice", category: "Famille", prompt: "Puériculture", keywords: ["puericultrice"] },
  { id: "orthophoniste_enfant", name: "Orthophoniste Enfant", category: "Famille", prompt: "Orthophonie enfants", keywords: ["orthophoniste enfant"] },
  { id: "psychologue_enfant", name: "Psychologue Enfant", category: "Famille", prompt: "Psychologie enfantine", keywords: ["psychologue enfant"] },
  { id: "animateur_centre", name: "Animateur Centre", category: "Famille", prompt: "Animation centre aéré", keywords: ["animateur centre"] },
  { id: "prof_des_ecoles", name: "Prof des Écoles", category: "Famille", prompt: "Enseignement primaire", keywords: ["prof des ecoles"] },
  { id: "assistante_sociale", name: "Assistante Sociale", category: "Famille", prompt: "Aide sociale", keywords: ["assistante sociale"] },
  { id: "conseiller_famille", name: "Conseiller Famille", category: "Famille", prompt: "Conseil familial", keywords: ["conseiller famille"] },
  { id: "conseiller_nutrition_enfant", name: "Nutritionniste Enfant", category: "Famille", prompt: "Nutrition enfants", keywords: ["nutrition enfant"] },
  { id: "prof_activites", name: "Prof Activités Enfants", category: "Famille", prompt: "Activités enfants", keywords: ["activites enfants"] },
  { id: "conteur", name: "Conteur", category: "Famille", prompt: "Contes pour enfants", keywords: ["conteur"] },
  { id: "magicien_enfant", name: "Magicien Enfants", category: "Famille", prompt: "Magie pour enfants", keywords: ["magicien enfant"] },
  { id: "clown", name: "Clown", category: "Famille", prompt: "Animation clown", keywords: ["clown"] },
  { id: "photographe_enfant", name: "Photographe Enfants", category: "Famille", prompt: "Photos enfants", keywords: ["photographe enfant"] },
  { id: "anniversaire", name: "Organisateur Anniversaire", category: "Famille", prompt: "Organisation anniversaires", keywords: ["anniversaire"] },
  { id: "fetes_enfants", name: "Fêtes Enfants", category: "Famille", prompt: "Organisation fêtes", keywords: ["fetes enfants"] },
  { id: "coach_scolaire", name: "Coach Scolaire", category: "Famille", prompt: "Coaching scolaire", keywords: ["coach scolaire"] },

  // ═══ ANIMAUX & NATURE (15) ═══
  { id: "dresseur_chien", name: "Dresseur de Chien", category: "Animaux", prompt: "Dressage canin", keywords: ["dresseur chien"] },
  { id: "comportementaliste", name: "Comportementaliste", category: "Animaux", prompt: "Comportement animaux", keywords: ["comportementaliste"] },
  { id: "toiletteur", name: "Toiletteur", category: "Animaux", prompt: "Toilettage", keywords: ["toiletteur"] },
  { id: "pension_animaux", name: "Pension Animaux", category: "Animaux", prompt: "Pension pour animaux", keywords: ["pension animaux"] },
  { id: "promeneur_chien", name: "Promeneur de Chien", category: "Animaux", prompt: "Promenade chiens", keywords: ["promeneur chien"] },
  { id: "eleveur", name: "Éleveur", category: "Animaux", prompt: "Élevage", keywords: ["eleveur"] },
  { id: "veterinaire_equin", name: "Vétérinaire Équin", category: "Animaux", prompt: "Vétérinaire chevaux", keywords: ["veterinaire equin"] },
  { id: "fauconnier", name: "Fauconnier", category: "Animaux", prompt: "Fauconnerie", keywords: ["fauconnier"] },
  { id: "apiculteur", name: "Apiculteur", category: "Nature", prompt: "Apiculture", keywords: ["apiculteur"] },
  { id: "agriculteur", name: "Agriculteur", category: "Nature", prompt: "Agriculture", keywords: ["agriculteur"] },
  { id: "maraicher", name: "Maraîcher", category: "Nature", prompt: "Maraîchage", keywords: ["maraicher"] },
  { id: "viticulteur", name: "Viticulteur", category: "Nature", prompt: "Viticulture", keywords: ["viticulteur"] },
  { id: "forestier", name: "Forestier", category: "Nature", prompt: "Sylviculture", keywords: ["forestier"] },
  { id: "botaniste", name: "Botaniste", category: "Nature", prompt: "Botanique", keywords: ["botaniste"] },
  { id: "ecologiste", name: "Écologiste", category: "Nature", prompt: "Écologie", keywords: ["ecologiste"] },

  // ═══ SCIENCES & RECHERCHE (20) ═══
  { id: "chercheur", name: "Chercheur", category: "Sciences", prompt: "Recherche scientifique", keywords: ["chercheur"] },
  { id: "biologiste_sci", name: "Biologiste", category: "Sciences", prompt: "Biologie", keywords: ["biologiste sci"] },
  { id: "chimiste", name: "Chimiste", category: "Sciences", prompt: "Chimie", keywords: ["chimiste"] },
  { id: "physicien", name: "Physicien", category: "Sciences", prompt: "Physique", keywords: ["physicien"] },
  { id: "mathematicien", name: "Mathématicien", category: "Sciences", prompt: "Mathématiques", keywords: ["mathematicien"] },
  { id: "astronome", name: "Astronome", category: "Sciences", prompt: "Astronomie", keywords: ["astronome"] },
  { id: "astrophysicien", name: "Astrophysicien", category: "Sciences", prompt: "Astrophysique", keywords: ["astrophysicien"] },
  { id: "geologue", name: "Géologue", category: "Sciences", prompt: "Géologie", keywords: ["geologue"] },
  { id: "meteorologiste", name: "Météorologiste", category: "Sciences", prompt: "Météorologie", keywords: ["meteorologiste"] },
  { id: "oceanographe", name: "Océanographe", category: "Sciences", prompt: "Océanographie", keywords: ["oceanographe"] },
  { id: "archeologue", name: "Archéologue", category: "Sciences", prompt: "Archéologie", keywords: ["archeologue"] },
  { id: "historien", name: "Historien", category: "Sciences", prompt: "Histoire", keywords: ["historien"] },
  { id: "sociologue", name: "Sociologue", category: "Sciences", prompt: "Sociologie", keywords: ["sociologue"] },
  { id: "anthropologue", name: "Anthropologue", category: "Sciences", prompt: "Anthropologie", keywords: ["anthropologue"] },
  { id: "linguiste", name: "Linguiste", category: "Sciences", prompt: "Linguistique", keywords: ["linguiste"] },
  { id: "philosophe", name: "Philosophe", category: "Sciences", prompt: "Philosophie", keywords: ["philosophe"] },
  { id: "economiste", name: "Économiste", category: "Sciences", prompt: "Économie", keywords: ["economiste"] },
  { id: "statisticien", name: "Statisticien", category: "Sciences", prompt: "Statistiques", keywords: ["statisticien"] },
  { id: "geneticien", name: "Généticien", category: "Sciences", prompt: "Génétique", keywords: ["geneticien"] },
  { id: "neuroscientifique", name: "Neuroscientifique", category: "Sciences", prompt: "Neurosciences", keywords: ["neuroscientifique"] },

  // ═══ SPORT & COACHING (15) ═══
  { id: "agent_sportif", name: "Agent Sportif", category: "Sport", prompt: "Agent de sportifs", keywords: ["agent sportif"] },
  { id: "manager_sport", name: "Manager Sportif", category: "Sport", prompt: "Management sportif", keywords: ["manager sportif"] },
  { id: "entraineur_pro", name: "Entraîneur Pro", category: "Sport", prompt: "Entraînement professionnel", keywords: ["entraineur pro"] },
  { id: "scout_foot", name: "Recruteur Football", category: "Sport", prompt: "Scouting football", keywords: ["scout football"] },
  { id: "arbitre", name: "Arbitre", category: "Sport", prompt: "Arbitrage", keywords: ["arbitre"] },
  { id: "commentateur", name: "Commentateur Sportif", category: "Sport", prompt: "Commentaire sportif", keywords: ["commentateur sport"] },
  { id: "journaliste_sport", name: "Journaliste Sportif", category: "Sport", prompt: "Journalisme sport", keywords: ["journaliste sport"] },
  { id: "preparateur_mental", name: "Préparateur Mental", category: "Sport", prompt: "Préparation mentale", keywords: ["preparateur mental"] },
  { id: "physiotherapeute", name: "Physiothérapeute", category: "Sport", prompt: "Physiothérapie", keywords: ["physiotherapeute"] },
  { id: "nutritionniste_sport", name: "Nutritionniste Sport", category: "Sport", prompt: "Nutrition sportive", keywords: ["nutritionniste sport"] },
  { id: "coach_basket_pro", name: "Coach Basket Pro", category: "Sport", prompt: "Coaching basket pro", keywords: ["coach basket pro"] },
  { id: "coach_foot_pro", name: "Coach Foot Pro", category: "Sport", prompt: "Coaching foot pro", keywords: ["coach foot pro"] },
  { id: "coach_rugby", name: "Coach Rugby", category: "Sport", prompt: "Coaching rugby", keywords: ["coach rugby"] },
  { id: "coach_handball", name: "Coach Handball", category: "Sport", prompt: "Coaching handball", keywords: ["coach handball"] },
  { id: "coach_volley", name: "Coach Volley", category: "Sport", prompt: "Coaching volley", keywords: ["coach volley"] },

  // ═══ LOISIRS & HOBBIES (15) ═══
  { id: "photographe_amateur", name: "Photographe Amateur", category: "Loisirs", prompt: "Photographie amateur", keywords: ["photographe amateur"] },
  { id: "astronome_amateur", name: "Astronome Amateur", category: "Loisirs", prompt: "Astronomie amateur", keywords: ["astronome amateur"] },
  { id: "collectionneur", name: "Collectionneur", category: "Loisirs", prompt: "Collections", keywords: ["collectionneur"] },
  { id: "modelisme", name: "Modéliste", category: "Loisirs", prompt: "Modélisme", keywords: ["modelisme"] },
  { id: "jeux_video", name: "Expert Jeux Vidéo", category: "Loisirs", prompt: "Jeux vidéo", keywords: ["jeux video"] },
  { id: "esport", name: "Coach eSport", category: "Loisirs", prompt: "Coaching eSport", keywords: ["esport"] },
  { id: "streamer_jeux", name: "Streamer Jeux Vidéo", category: "Loisirs", prompt: "Streaming gaming", keywords: ["streamer jeux"] },
  { id: "blogger_jeux", name: "Blogger Jeux Vidéo", category: "Loisirs", prompt: "Blog gaming", keywords: ["blogger jeux"] },
  { id: "testeur_jeux", name: "Testeur Jeux Vidéo", category: "Loisirs", prompt: "Tests de jeux", keywords: ["testeur jeux"] },
  { id: "speedrunner", name: "Speedrunner", category: "Loisirs", prompt: "Speedrun", keywords: ["speedrun"] },
  { id: "cosplay", name: "Cosplay", category: "Loisirs", prompt: "Cosplay", keywords: ["cosplay"] },
  { id: "danse_urbaine", name: "Danse Urbaine", category: "Loisirs", prompt: "Danses urbaines", keywords: ["danse urbaine"] },
  { id: "jardinage", name: "Expert Jardinage", category: "Loisirs", prompt: "Jardinage", keywords: ["jardinage"] },
  { id: "bricolage", name: "Expert Bricolage", category: "Loisirs", prompt: "Bricolage", keywords: ["bricolage"] },
  { id: "magie", name: "Magicien", category: "Loisirs", prompt: "Magie", keywords: ["magie"] },

  // ═══ DIVERS (6) ═══
  { id: "coach_general", name: "Coach Polyvalent", category: "Divers", prompt: "Accompagnement général", keywords: ["coach"] },
  { id: "assistant_ia", name: "Assistant IA", category: "Divers", prompt: "Assistant intelligent généraliste", keywords: ["assistant"] },
  { id: "conseiller", name: "Conseiller", category: "Divers", prompt: "Conseil général", keywords: ["conseiller"] },
  { id: "expert_multi", name: "Expert Multidisciplinaire", category: "Divers", prompt: "Expertise variée", keywords: ["expert multidisciplinaire"] },
  { id: "consultant_general", name: "Consultant Général", category: "Divers", prompt: "Conseil en tout domaine", keywords: ["consultant general"] },
  { id: "traducteur_universel", name: "Traducteur Universel", category: "Divers", prompt: "Traduction toutes langues", keywords: ["traducteur universel"] },
];

// ⭐ Trouve un agent à partir d'un prompt
export function findAgent(prompt: string): Agent | null {
  const lower = prompt.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").trim();

  // 1. Recherche par mot-clé exact
  for (const agent of AGENTS) {
    for (const kw of agent.keywords) {
      const kwNorm = kw.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
      if (lower === kwNorm || lower.includes(kwNorm)) {
        return agent;
      }
    }
  }

  // 2. Recherche par nom
  for (const agent of AGENTS) {
    const nameNorm = agent.name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    if (lower.includes(nameNorm)) {
      return agent;
    }
  }

  return null;
}

export const TOTAL_AGENTS = AGENTS.length;