// src/lib/codeAgents.ts
// ⭐ 120 agents Code & Logiciel

export type CodeAgent = {
  id: string;
  name: string;
  category: string;
  prompt: string;
  keywords: string[];
};

export const CODE_AGENTS: CodeAgent[] = [
  // ═══ LANGAGES DE PROGRAMMATION (30) ═══
  { id: "dev_js", name: "Dev JavaScript", category: "Code", prompt: "JavaScript vanilla, ES6+, DOM, async/await", keywords: ["javascript", "js"] },
  { id: "dev_ts", name: "Dev TypeScript", category: "Code", prompt: "TypeScript, types avancés, génériques", keywords: ["typescript", "ts"] },
  { id: "dev_python2", name: "Dev Python", category: "Code", prompt: "Python 3, POO, décorateurs, async", keywords: ["python3", "py"] },
  { id: "dev_rust2", name: "Dev Rust", category: "Code", prompt: "Rust, ownership, borrow checker, cargo", keywords: ["rust lang", "cargo"] },
  { id: "dev_go2", name: "Dev Golang", category: "Code", prompt: "Go, goroutines, channels, interfaces", keywords: ["golang", "go lang"] },
  { id: "dev_java2", name: "Dev Java", category: "Code", prompt: "Java 17+, JVM, collections, streams", keywords: ["java 17", "jvm"] },
  { id: "dev_csharp", name: "Dev C#", category: "Code", prompt: "C#, LINQ, async, .NET", keywords: ["c#", "csharp", "dotnet"] },
  { id: "dev_cpp2", name: "Dev C++", category: "Code", prompt: "C++ moderne, STL, templates, RAII", keywords: ["cpp", "c plus plus"] },
  { id: "dev_c", name: "Dev C", category: "Code", prompt: "C, pointeurs, mémoire, systèmes", keywords: ["c lang", "language c"] },
  { id: "dev_php2", name: "Dev PHP", category: "Code", prompt: "PHP 8, POO, PSR, composer", keywords: ["php8", "php modern"] },
  { id: "dev_ruby2", name: "Dev Ruby", category: "Code", prompt: "Ruby, blocks, gems, metaprogramming", keywords: ["ruby lang"] },
  { id: "dev_kotlin", name: "Dev Kotlin", category: "Code", prompt: "Kotlin, coroutines, Android natif", keywords: ["kotlin"] },
  { id: "dev_swift", name: "Dev Swift", category: "Code", prompt: "Swift, SwiftUI, iOS natif", keywords: ["swift", "ios dev"] },
  { id: "dev_scala", name: "Dev Scala", category: "Code", prompt: "Scala, functional programming, Akka", keywords: ["scala"] },
  { id: "dev_elixir", name: "Dev Elixir", category: "Code", prompt: "Elixir, Phoenix, OTP", keywords: ["elixir", "phoenix"] },
  { id: "dev_haskell", name: "Dev Haskell", category: "Code", prompt: "Haskell, monades, types purs", keywords: ["haskell"] },
  { id: "dev_clojure", name: "Dev Clojure", category: "Code", prompt: "Clojure, Lisp, immutabilité", keywords: ["clojure"] },
  { id: "dev_lua", name: "Dev Lua", category: "Code", prompt: "Lua, scripting, jeux, Roblox", keywords: ["lua"] },
  { id: "dev_perl", name: "Dev Perl", category: "Code", prompt: "Perl, regex, scripting système", keywords: ["perl"] },
  { id: "dev_r", name: "Dev R", category: "Code", prompt: "R, statistiques, data science", keywords: ["r lang", "rlang"] },
  { id: "dev_matlab", name: "Dev MATLAB", category: "Code", prompt: "MATLAB, ingénierie, simulations", keywords: ["matlab"] },
  { id: "dev_dart", name: "Dev Dart", category: "Code", prompt: "Dart, Flutter", keywords: ["dart"] },
  { id: "dev_asm", name: "Dev Assembleur", category: "Code", prompt: "Assembleur x86, ARM, bas niveau", keywords: ["assembleur", "assembly", "asm"] },
  { id: "dev_bash", name: "Dev Bash", category: "Code", prompt: "Bash, scripting shell, automatisation", keywords: ["bash", "shell"] },
  { id: "dev_powershell", name: "Dev PowerShell", category: "Code", prompt: "PowerShell, scripting Windows", keywords: ["powershell"] },
  { id: "dev_zsh", name: "Dev Zsh", category: "Code", prompt: "Zsh, config shell, productivité", keywords: ["zsh"] },
  { id: "dev_vb", name: "Dev VB.NET", category: "Code", prompt: "Visual Basic .NET", keywords: ["vb.net", "visual basic"] },
  { id: "dev_fsharp", name: "Dev F#", category: "Code", prompt: "F#, functional .NET", keywords: ["f#", "fsharp"] },
  { id: "dev_solidity", name: "Dev Solidity", category: "Code", prompt: "Solidity, smart contracts", keywords: ["solidity"] },
  { id: "dev_zig", name: "Dev Zig", category: "Code", prompt: "Zig, systèmes, sécurité", keywords: ["zig"] },

  // ═══ FRAMEWORKS FRONT (20) ═══
  { id: "fw_react", name: "Dev React", category: "Code", prompt: "React 18+, hooks, context, suspense", keywords: ["react", "reactjs"] },
  { id: "fw_next", name: "Dev Next.js", category: "Code", prompt: "Next.js 14+, App Router, RSC, SSR", keywords: ["next", "nextjs"] },
  { id: "fw_vue", name: "Dev Vue.js", category: "Code", prompt: "Vue 3, Composition API, Pinia", keywords: ["vue", "vuejs"] },
  { id: "fw_nuxt", name: "Dev Nuxt", category: "Code", prompt: "Nuxt 3, SSR Vue", keywords: ["nuxt", "nuxtjs"] },
  { id: "fw_angular", name: "Dev Angular", category: "Code", prompt: "Angular 17+, RxJS, signals", keywords: ["angular"] },
  { id: "fw_svelte", name: "Dev Svelte", category: "Code", prompt: "Svelte, SvelteKit", keywords: ["svelte", "sveltekit"] },
  { id: "fw_solid", name: "Dev SolidJS", category: "Code", prompt: "SolidJS, réactivité fine", keywords: ["solid", "solidjs"] },
  { id: "fw_astro", name: "Dev Astro", category: "Code", prompt: "Astro, sites statiques", keywords: ["astro"] },
  { id: "fw_remix", name: "Dev Remix", category: "Code", prompt: "Remix, data loading", keywords: ["remix"] },
  { id: "fw_qwik", name: "Dev Qwik", category: "Code", prompt: "Qwik, résumabilité", keywords: ["qwik"] },
  { id: "fw_alpine", name: "Dev Alpine.js", category: "Code", prompt: "Alpine.js, HTML interactif", keywords: ["alpine"] },
  { id: "fw_htmx", name: "Dev HTMX", category: "Code", prompt: "HTMX, HTML dynamique", keywords: ["htmx"] },
  { id: "fw_tailwind", name: "Dev Tailwind", category: "Code", prompt: "Tailwind CSS, utility-first", keywords: ["tailwind", "tailwindcss"] },
  { id: "fw_bootstrap", name: "Dev Bootstrap", category: "Code", prompt: "Bootstrap 5, responsive", keywords: ["bootstrap"] },
  { id: "fw_sass", name: "Dev Sass/SCSS", category: "Code", prompt: "Sass, SCSS, préprocesseurs CSS", keywords: ["sass", "scss"] },
  { id: "fw_css", name: "Dev CSS Expert", category: "Code", prompt: "CSS moderne, grid, flexbox, animations", keywords: ["css expert"] },
  { id: "fw_shadcn", name: "Dev shadcn/ui", category: "Code", prompt: "shadcn/ui, Radix, composants", keywords: ["shadcn"] },
  { id: "fw_mui", name: "Dev Material UI", category: "Code", prompt: "Material UI, MUI, React", keywords: ["mui", "material ui"] },
  { id: "fw_chakra", name: "Dev Chakra UI", category: "Code", prompt: "Chakra UI, composants", keywords: ["chakra"] },
  { id: "fw_three", name: "Dev Three.js", category: "Code", prompt: "Three.js, WebGL, 3D web", keywords: ["three", "threejs", "webgl"] },

  // ═══ FRAMEWORKS BACK (20) ═══
  { id: "be_node", name: "Dev Node.js", category: "Code", prompt: "Node.js, fs, streams, workers", keywords: ["node", "nodejs"] },
  { id: "be_express", name: "Dev Express", category: "Code", prompt: "Express.js, middleware, routes", keywords: ["express", "expressjs"] },
  { id: "be_nest", name: "Dev NestJS", category: "Code", prompt: "NestJS, DI, décorateurs", keywords: ["nest", "nestjs"] },
  { id: "be_fastify", name: "Dev Fastify", category: "Code", prompt: "Fastify, performance Node", keywords: ["fastify"] },
  { id: "be_django", name: "Dev Django", category: "Code", prompt: "Django, ORM, admin", keywords: ["django"] },
  { id: "be_flask", name: "Dev Flask", category: "Code", prompt: "Flask, blueprints, extensions", keywords: ["flask"] },
  { id: "be_fastapi", name: "Dev FastAPI", category: "Code", prompt: "FastAPI, Pydantic, async Python", keywords: ["fastapi"] },
  { id: "be_laravel", name: "Dev Laravel", category: "Code", prompt: "Laravel 11, Eloquent, artisan", keywords: ["laravel"] },
  { id: "be_symfony", name: "Dev Symfony", category: "Code", prompt: "Symfony, bundles, doctrine", keywords: ["symfony"] },
  { id: "be_rails", name: "Dev Ruby on Rails", category: "Code", prompt: "Rails, ActiveRecord, MVC", keywords: ["rails", "ruby on rails"] },
  { id: "be_spring", name: "Dev Spring Boot", category: "Code", prompt: "Spring Boot, JPA, microservices", keywords: ["spring", "springboot"] },
  { id: "be_quarkus", name: "Dev Quarkus", category: "Code", prompt: "Quarkus, GraalVM, cloud-native Java", keywords: ["quarkus"] },
  { id: "be_aspnet", name: "Dev ASP.NET", category: "Code", prompt: "ASP.NET Core, C# web", keywords: ["aspnet", "asp.net"] },
  { id: "be_phoenix", name: "Dev Phoenix", category: "Code", prompt: "Phoenix Elixir, LiveView", keywords: ["phoenix elixir"] },
  { id: "be_gin", name: "Dev Gin", category: "Code", prompt: "Gin Go, API HTTP", keywords: ["gin go"] },
  { id: "be_fiber", name: "Dev Fiber", category: "Code", prompt: "Fiber Go, web framework", keywords: ["fiber go"] },
  { id: "be_actix", name: "Dev Actix", category: "Code", prompt: "Actix Rust, web", keywords: ["actix"] },
  { id: "be_axum", name: "Dev Axum", category: "Code", prompt: "Axum Rust, tokio", keywords: ["axum"] },
  { id: "be_trpc", name: "Dev tRPC", category: "Code", prompt: "tRPC, TypeScript end-to-end", keywords: ["trpc"] },
  { id: "be_graphql", name: "Dev GraphQL", category: "Code", prompt: "GraphQL, Apollo, schema", keywords: ["graphql", "apollo"] },

  // ═══ BASES DE DONNÉES (15) ═══
  { id: "db_postgres", name: "Expert PostgreSQL", category: "Data", prompt: "PostgreSQL, PL/pgSQL, index", keywords: ["postgres", "postgresql"] },
  { id: "db_mysql", name: "Expert MySQL", category: "Data", prompt: "MySQL, MariaDB, tuning", keywords: ["mysql", "mariadb"] },
  { id: "db_mongo", name: "Expert MongoDB", category: "Data", prompt: "MongoDB, aggregation, sharding", keywords: ["mongo", "mongodb"] },
  { id: "db_redis", name: "Expert Redis", category: "Data", prompt: "Redis, cache, pub/sub", keywords: ["redis"] },
  { id: "db_sqlite", name: "Expert SQLite", category: "Data", prompt: "SQLite, embarqué", keywords: ["sqlite"] },
  { id: "db_supabase", name: "Expert Supabase", category: "Data", prompt: "Supabase, auth, realtime", keywords: ["supabase"] },
  { id: "db_firebase", name: "Expert Firebase", category: "Data", prompt: "Firebase, Firestore, auth", keywords: ["firebase"] },
  { id: "db_prisma", name: "Expert Prisma", category: "Data", prompt: "Prisma ORM, migrations", keywords: ["prisma"] },
  { id: "db_drizzle", name: "Expert Drizzle", category: "Data", prompt: "Drizzle ORM, TypeScript", keywords: ["drizzle"] },
  { id: "db_clickhouse", name: "Expert ClickHouse", category: "Data", prompt: "ClickHouse, analytics temps réel", keywords: ["clickhouse"] },
  { id: "db_elastic", name: "Expert Elasticsearch", category: "Data", prompt: "Elasticsearch, recherche", keywords: ["elastic", "elasticsearch"] },
  { id: "db_cassandra", name: "Expert Cassandra", category: "Data", prompt: "Cassandra, NoSQL distribué", keywords: ["cassandra"] },
  { id: "db_neo4j", name: "Expert Neo4j", category: "Data", prompt: "Neo4j, base graphe", keywords: ["neo4j", "graphe"] },
  { id: "db_pinecone", name: "Expert Pinecone", category: "Data", prompt: "Pinecone, vector database", keywords: ["pinecone", "vector db"] },
  { id: "db_weaviate", name: "Expert Weaviate", category: "Data", prompt: "Weaviate, vector search", keywords: ["weaviate"] },

  // ═══ DEVOPS / CLOUD (15) ═══
  { id: "ops_docker", name: "Expert Docker", category: "Software", prompt: "Docker, images, compose", keywords: ["docker"] },
  { id: "ops_k8s", name: "Expert Kubernetes", category: "Software", prompt: "Kubernetes, pods, helm", keywords: ["kubernetes", "k8s"] },
  { id: "ops_terraform", name: "Expert Terraform", category: "Software", prompt: "Terraform, IaC", keywords: ["terraform"] },
  { id: "ops_ansible", name: "Expert Ansible", category: "Software", prompt: "Ansible, playbooks", keywords: ["ansible"] },
  { id: "ops_aws", name: "Expert AWS", category: "Cloud", prompt: "AWS, EC2, S3, Lambda", keywords: ["aws", "amazon web"] },
  { id: "ops_gcp", name: "Expert GCP", category: "Cloud", prompt: "Google Cloud Platform", keywords: ["gcp", "google cloud"] },
  { id: "ops_azure", name: "Expert Azure", category: "Cloud", prompt: "Microsoft Azure", keywords: ["azure"] },
  { id: "ops_vercel", name: "Expert Vercel", category: "Cloud", prompt: "Vercel, deploy Next.js", keywords: ["vercel"] },
  { id: "ops_netlify", name: "Expert Netlify", category: "Cloud", prompt: "Netlify, JAMstack", keywords: ["netlify"] },
  { id: "ops_cloudflare", name: "Expert Cloudflare", category: "Cloud", prompt: "Cloudflare, Workers, CDN", keywords: ["cloudflare"] },
  { id: "ops_github", name: "Expert GitHub", category: "Software", prompt: "GitHub, Actions, workflows", keywords: ["github"] },
  { id: "ops_gitlab", name: "Expert GitLab", category: "Software", prompt: "GitLab, CI/CD", keywords: ["gitlab"] },
  { id: "ops_jenkins", name: "Expert Jenkins", category: "Software", prompt: "Jenkins, pipelines", keywords: ["jenkins"] },
  { id: "ops_nginx", name: "Expert Nginx", category: "Software", prompt: "Nginx, reverse proxy", keywords: ["nginx"] },
  { id: "ops_linux", name: "Expert Linux", category: "Software", prompt: "Linux, bash, administration", keywords: ["linux", "ubuntu", "debian"] },

  // ═══ IA / ML (12) ═══
  { id: "ai_openai", name: "Expert OpenAI API", category: "AI", prompt: "OpenAI API, GPT, function calling", keywords: ["openai api", "gpt api"] },
  { id: "ai_claude", name: "Expert Claude API", category: "AI", prompt: "Anthropic Claude API, tools", keywords: ["claude api", "anthropic"] },
  { id: "ai_langchain", name: "Expert LangChain", category: "AI", prompt: "LangChain, agents, RAG", keywords: ["langchain"] },
  { id: "ai_llamaindex", name: "Expert LlamaIndex", category: "AI", prompt: "LlamaIndex, RAG avancé", keywords: ["llamaindex"] },
  { id: "ai_tensorflow", name: "Expert TensorFlow", category: "AI", prompt: "TensorFlow, Keras, deep learning", keywords: ["tensorflow", "keras"] },
  { id: "ai_pytorch", name: "Expert PyTorch", category: "AI", prompt: "PyTorch, réseaux de neurones", keywords: ["pytorch"] },
  { id: "ai_huggingface", name: "Expert Hugging Face", category: "AI", prompt: "Hugging Face, transformers", keywords: ["hugging face", "huggingface"] },
  { id: "ai_stablediffusion", name: "Expert Stable Diffusion", category: "AI", prompt: "Stable Diffusion, génération d'images", keywords: ["stable diffusion"] },
  { id: "ai_prompt", name: "Expert Prompt Engineering", category: "AI", prompt: "Prompts optimisés, LLM", keywords: ["prompt", "prompt engineering"] },
  { id: "ai_rag", name: "Expert RAG", category: "AI", prompt: "RAG, retrieval augmented generation", keywords: ["rag"] },
  { id: "ai_finetuning", name: "Expert Fine-Tuning", category: "AI", prompt: "Fine-tuning LLM, LoRA", keywords: ["fine-tuning", "finetuning", "lora"] },
  { id: "ai_agents", name: "Expert AI Agents", category: "AI", prompt: "Agents IA, tools, function calling", keywords: ["ai agents", "agents ia"] },

  // ═══ WEB3 / BLOCKCHAIN (6) ═══
  { id: "w3_eth", name: "Expert Ethereum", category: "Web3", prompt: "Ethereum, EVM, gas", keywords: ["ethereum", "eth"] },
  { id: "w3_sol", name: "Expert Solana", category: "Web3", prompt: "Solana, Rust on-chain", keywords: ["solana"] },
  { id: "w3_web3", name: "Expert Web3.js", category: "Web3", prompt: "Web3.js, ethers.js", keywords: ["web3", "web3js"] },
  { id: "w3_nft", name: "Expert NFT", category: "Web3", prompt: "NFT, ERC-721, minting", keywords: ["nft"] },
  { id: "w3_defi", name: "Expert DeFi", category: "Web3", prompt: "DeFi, protocoles, yield", keywords: ["defi"] },
  { id: "w3_audit", name: "Auditeur Smart Contract", category: "Web3", prompt: "Audit Solidity, sécurité", keywords: ["audit smart contract"] },

  // ═══ GAME DEV (7) ═══
  { id: "g_unity", name: "Dev Unity", category: "GameDev", prompt: "Unity, C#, jeu 2D/3D", keywords: ["unity", "unity3d"] },
  { id: "g_unreal", name: "Dev Unreal Engine", category: "GameDev", prompt: "Unreal Engine 5, Blueprints", keywords: ["unreal", "unreal engine"] },
  { id: "g_godot", name: "Dev Godot", category: "GameDev", prompt: "Godot 4, GDScript", keywords: ["godot"] },
  { id: "g_phaser", name: "Dev Phaser", category: "GameDev", prompt: "Phaser 3, jeux HTML5", keywords: ["phaser"] },
  { id: "g_pixi", name: "Dev PixiJS", category: "GameDev", prompt: "PixiJS, 2D WebGL", keywords: ["pixi", "pixijs"] },
  { id: "g_game_design", name: "Game Designer", category: "GameDev", prompt: "Game design, level design", keywords: ["game design", "game designer"] },
  { id: "g_game_art", name: "Game Artist", category: "GameDev", prompt: "Art de jeu, sprites, 3D", keywords: ["game artist"] },

  // ═══ OUTILS DEV (12) ═══
  { id: "t_git", name: "Expert Git", category: "Software", prompt: "Git, branches, rebase, workflow", keywords: ["git"] },
  { id: "t_vscode", name: "Expert VS Code", category: "Software", prompt: "VS Code, extensions, settings", keywords: ["vscode", "vs code"] },
  { id: "t_vim", name: "Expert Vim/Neovim", category: "Software", prompt: "Vim, Neovim, motions", keywords: ["vim", "neovim"] },
  { id: "t_regex", name: "Expert Regex", category: "Software", prompt: "Regex, patterns, expressions régulières", keywords: ["regex", "regexp"] },
  { id: "t_jest", name: "Expert Jest", category: "Software", prompt: "Jest, tests unitaires JS", keywords: ["jest"] },
  { id: "t_vitest", name: "Expert Vitest", category: "Software", prompt: "Vitest, tests rapides", keywords: ["vitest"] },
  { id: "t_cypress", name: "Expert Cypress", category: "Software", prompt: "Cypress, tests E2E", keywords: ["cypress"] },
  { id: "t_playwright", name: "Expert Playwright", category: "Software", prompt: "Playwright, tests browser", keywords: ["playwright"] },
  { id: "t_puppeteer", name: "Expert Puppeteer", category: "Software", prompt: "Puppeteer, scraping", keywords: ["puppeteer"] },
  { id: "t_postman", name: "Expert Postman", category: "Software", prompt: "Postman, tests API", keywords: ["postman"] },
  { id: "t_figma", name: "Expert Figma", category: "Software", prompt: "Figma, design UI", keywords: ["figma"] },
  { id: "t_notion", name: "Expert Notion", category: "Software", prompt: "Notion, docs, bases", keywords: ["notion"] },
];